const QUIZ_CATEGORIES = [
  { id: 'transformer', label: 'Transformer', icon: '⚡', accent: '#fde68a' },
  { id: 'llm', label: 'LLM核心', icon: '🧠', accent: '#fdba74' },
  { id: 'vit', label: 'ViT/视觉', icon: '👁️', accent: '#7dd3fc' },
  { id: 'clip', label: 'CLIP/对比学习', icon: '🔗', accent: '#5eead4' },
  { id: 'vlm', label: 'VLM架构', icon: '🏗️', accent: '#c4b5fd' },
  { id: 'training', label: '训练策略', icon: '🎯', accent: '#f0abfc' },
  { id: 'inference', label: '推理优化', icon: '🚀', accent: '#6ee7b7' },
  { id: 'tokenization', label: 'Tokenization', icon: '🧩', accent: '#67e8f9' },
  { id: 'reasoning', label: '推理/CoT', icon: '💡', accent: '#fca5a5' },
  { id: 'generation', label: '生成模型', icon: '🎨', accent: '#d8b4fe' },
  { id: 'rag', label: 'RAG/检索增强', icon: '📚', accent: '#86efac' },
  { id: 'frontier', label: '前沿架构', icon: '🔬', accent: '#fb7185' },
];

const QUIZ_QUESTIONS = [
  // ===== Transformer 深度 =====
  { cat:'transformer', q:'假设Q和K的每个元素独立服从均值0、方差1的分布，d_k=64时，QK^T中单个元素的方差是多少？为什么这会导致问题？', opts:['方差=64，softmax梯度消失','方差=8，计算溢出','方差=4096，数值不稳定','方差=1，没有问题'], ans:0, exp:'QK^T的每个元素是d_k个独立随机变量乘积之和，方差=d_k=64。方差大→部分值很大→softmax输出趋近one-hot→梯度≈0。除以√64=8使方差归一为1。这不仅是"归一化"，而是严格的方差控制。' },
  { cat:'transformer', q:'RoPE在外推到训练长度2×时性能急剧下降，YaRN的核心解决思路是什么？', opts:['直接截断超长位置','对不同频率分量采用不同的插值策略(NTK-by-parts)，高频保持、低频插值','用ALiBi替换RoPE','增大base frequency到1M'], ans:1, exp:'YaRN发现RoPE不同频率分量对外推的敏感度不同：高频分量编码局部关系（不该被插值），低频分量编码全局位置（需要插值）。NTK-by-parts对频率做分段处理，加上temperature scaling修正attention entropy。这比NTK-Aware Interpolation更精细。' },
  { cat:'transformer', q:'Flash Attention 2相比Flash Attention 1的关键优化是什么？', opts:['降低了计算复杂度从O(n²)到O(n)','将外层循环改为沿Q遍历、内层沿KV遍历，减少非矩阵乘FLOPs并提高并行度','引入了稀疏attention','使用了INT8计算'], ans:1, exp:'FA1外层遍历KV、内层遍历Q，需要频繁更新全局softmax归一化因子；FA2调换循环顺序(外Q内KV)，每个Q tile的softmax上下文更局部，减少了约50%的非GEMM FLOPs。同时改进了warp间的工作划分，在A100上达到理论峰值的72%（FA1仅55%）。' },
  { cat:'transformer', q:'MHA/MQA/GQA在KV Cache显存占用上的量化对比：32层、hidden=4096、32 heads、序列长度8192、FP16，三者各需多少GB？', opts:['MHA=16GB, MQA=0.5GB, GQA(8组)=4GB','MHA=4GB, MQA=0.125GB, GQA(8组)=1GB','MHA=8GB, MQA=0.25GB, GQA(8组)=2GB','MHA=2GB, MQA=0.0625GB, GQA(8组)=0.5GB'], ans:2, exp:'KV Cache大小=2(K和V)×层数×序列长×head数×head_dim×2(FP16字节)。MHA: 2×32×8192×32×128×2=8GB; MQA: 只有1个KV head, =8/32=0.25GB; GQA(8组): 8个KV head, =8×(8/32)=2GB。这也是为什么GQA成为主流——在MHA 1/4的KV Cache开销下保留了大部分表达力。' },
  { cat:'transformer', q:'Pre-Norm Transformer在理论上存在"rank collapse"问题，具体指什么？为什么实际中影响不大？', opts:['梯度坍缩为零','残差连接使得深层token表示趋向同一方向，有效秩降低','注意力权重全部相等','参数矩阵秩不足'], ans:1, exp:'Pre-Norm结构中，残差路径上的Norm→Attention/FFN需要通过一个"收缩"的变换，经过多层后残差的贡献占主导，各token表示趋于线性相关(representation collapse)。DeepNorm(Post-Norm+缩放)和Sub-LN试图缓解此问题。实际中因为数据多样性和足够宽度（hidden_size大），问题不显著，但在千层级别会浮现。' },
  { cat:'transformer', q:'Sliding Window Attention(如Mistral)在第L层时，每个token的有效感受野大小是多少？（窗口大小为W）', opts:['W','L × W','W^L','min(L×W, n)'], ans:3, exp:'第1层每个token看到W个位置；第2层通过residual+attention，可以聚合前一层W范围内的信息，等效感受野扩展到2W。第L层的有效感受野为min(L×W, n)。Mistral用W=4096、32层，有效感受野=32×4096=131K，远超它的training length。这是SWA能处理长序列的理论依据。' },
  { cat:'transformer', q:'为什么现代LLM普遍用RMSNorm替代LayerNorm？除了"更快"之外还有什么深层原因？', opts:['精度更高','去掉mean-centering后梯度信号保留更好，避免了LN的hidden zero-mean约束对表达力的限制','参数量更少','没有深层原因，纯粹更快'], ans:1, exp:'LayerNorm先减均值再除标准差，强制hidden向量零均值。RMSNorm只做除以RMS（均方根），保留了均值信息。研究表明LN的re-centering操作实际贡献很小但引入了额外计算和约束。RMSNorm在保持训练稳定性的同时减少约7-10%的计算，且不损失表达力。关键是理论上re-centering对梯度流不是必需的。' },
  { cat:'transformer', q:'在MoE中，Expert Parallelism的通信瓶颈是什么？DeepSeek-V3如何缓解？', opts:['All-Reduce梯度通信','All-to-All dispatch/combine的延迟，DeepSeek-V3用辅助loss-free的负载均衡+通信计算overlap','Parameter Server瓶颈','KV Cache同步'], ans:1, exp:'MoE的Expert Parallelism需要All-to-All将token分发到对应Expert所在的GPU，再收集结果。当Expert跨节点时，这成为带宽瓶颈。DeepSeek-V3取消了辅助balance loss(用bias term动态调节路由概率)，让路由更自然+减少冗余通信，同时用FP8 GEMM和通信-计算pipeline overlap来隐藏延迟。' },

  // ===== LLM 核心深度 =====
  { cat:'llm', q:'DPO的loss函数中，β参数的含义和调参陷阱是什么？', opts:['学习率缩放因子','控制偏好强度的温度参数：β太大→模型忽略偏好信号，β太小→过拟合chosen/rejected导致reward hacking','正则化系数','梯度裁剪阈值'], ans:1, exp:'DPO loss = -log σ(β(log π(y_w)/π_ref(y_w) - log π(y_l)/π_ref(y_l)))。β是KL约束强度：β→∞时loss对偏好信号不敏感（太保守），β→0时模型完全拟合偏好对（可能reward hacking或崩溃）。实践中β=0.1~0.5，且需要关注chosen/rejected的reward margin是否在合理增长。' },
  { cat:'llm', q:'LoRA中，矩阵B初始化为零、A初始化为正态分布的设计原因是什么？', opts:['随机初始化效果一样好','保证训练开始时ΔW=BA=0，即从预训练权重开始而非随机扰动','减少计算量','防止梯度消失'], ans:1, exp:'若B和A都随机初始化，ΔW=BA≠0，等于在训练开始就给预训练模型加了一个随机扰动，会破坏已有能力。B=0保证初始时ΔW=0（模型行为完全等于预训练），然后通过梯度更新逐步学到有意义的adaptation。这是一个精巧的"warm start"设计。' },
  { cat:'llm', q:'Chinchilla Scaling Law相比Kaplan Scaling Law的核心修正是什么？这对实践产生了什么影响？', opts:['要求更大的模型','指出最优分配应该是模型参数N和数据量D等比扩展，而非Kaplan认为的优先扩参数','要求更长的训练','要求更大的batch size'], ans:1, exp:'Kaplan(2020)认为在固定compute下应优先增大N（参数），D（数据）可以较少。Chinchilla(2022)通过400+实验修正：最优的N和D应等比例增长（约1:20比例，每个参数对应约20个token）。影响深远：LLaMA/Qwen等后续模型都采用了"较小模型+充分训练"的策略，而非盲目扩大参数。' },
  { cat:'llm', q:'RLHF中Reward Model训练的一个关键工程陷阱是什么？', opts:['数据太多','Reward hacking：RM对分布外样本给出虚高reward，导致PPO策略学到"欺骗"RM的pattern而非真正提升质量','学习率太高','显存不足'], ans:1, exp:'RM是在有限偏好数据上训练的，对OOD输入可能给出不准确的高reward。PPO作为强RL优化器，会快速找到这些RM的"盲点"——生成高reward但低质量的文本(如过度verbose、重复、谄媚)。缓解方案包括：KL约束(防止策略偏离太远)、RLHF后再训RM、使用ensemble RM、DPO(完全绕过RM)。' },
  { cat:'llm', q:'AdamW中的weight decay和L2 regularization在Adam优化器下是否等价？', opts:['完全等价','不等价：L2是在loss中加‖w‖²项影响梯度，而AdamW的decoupled weight decay是直接在参数更新时减去λw，后者不受Adam的二阶矩缩放影响', '只在学习率恒定时等价','取决于batch size'], ans:1, exp:'在SGD中两者等价，但在Adam中L2正则的梯度2λw也会被Adam的v_t(二阶矩)缩放，导致对不同参数的正则强度不一致。AdamW的decoupled方式直接做w←w-lr×λ×w，正则强度与梯度统计无关，更合理。这是Loshchilov 2019的关键发现，对大模型训练稳定性影响显著。' },
  { cat:'llm', q:'在长上下文LLM训练中，为什么不能简单地将RoPE的base从10000提高到1000000来支持更长序列？', opts:['计算溢出','高频分量的分辨率急剧下降，相邻位置的旋转角差异变得极小，模型无法区分近距离的token位置关系','显存不够','梯度消失'], ans:1, exp:'RoPE的频率θ_i = base^(-2i/d)。base增大使所有频率降低。高频分量（i小的）本负责编码局部位置关系，base过大后角度差异Δθ→0，相邻token的位置编码几乎相同。这就是为什么需要YaRN/NTK-by-parts等方法分频段处理，而非简单改base。' },

  // ===== ViT 深度 =====
  { cat:'vit', q:'ViT中[CLS] token和全局平均池化(GAP)哪个更好？为什么InternViT选择了不同的方案？', opts:['[CLS]永远更好','GAP更好因为利用了所有patch信息，但VLM中需要保留所有patch token而非只取[CLS]，因此InternViT输出全部patch token给Projector','两者完全等价','取决于数据集大小'], ans:1, exp:'分类任务中GAP通常≥[CLS]，因为[CLS]是"额外"token需要学会聚合全局信息。但在VLM场景中，关键不是分类而是将空间信息传给LLM，因此InternViT/SigLIP等输出所有patch token（去掉[CLS]），让Projector/LLM自己决定关注什么。这是一个被面试者常忽略的设计细节。' },
  { cat:'vit', q:'DINOv2的student-teacher self-distillation中，teacher网络的更新策略是什么？为什么不能简单地让teacher=student？', opts:['teacher用更大的模型','teacher通过student权重的EMA更新，直接复制会导致模式坍缩(mode collapse)','teacher单独训练','teacher冻结不更新'], ans:1, exp:'Teacher是Student权重的指数移动平均(EMA): θ_t = λθ_t + (1-λ)θ_s。如果teacher=student（同一网络），就变成了trivial solution——输出常数即可最小化蒸馏loss。EMA提供了一个"慢更新"的稳定目标，类似于Mean Teacher/BYOL的设计哲学。另外teacher还使用centering来防止某一维度坍缩。' },
  { cat:'vit', q:'MAE(Masked Autoencoder)为什么选择75%这么高的mask ratio？这与BERT的15%有何设计哲学差异？', opts:['随机选择','图像信息冗余度远高于文本：相邻patch高度相关，低mask率时模型仅靠插值就能重建，学不到高层语义','只是为了加速训练','75%是实验最优，没有理论解释'], ans:1, exp:'文本每个token都携带独立语义信息(信息密度高)，15% mask就足够。图像patch间空间冗余极高，mask 50%时模型仅靠局部纹理插值就能"做弊"重建。75% mask迫使模型必须理解全局语义结构才能推断缺失内容。这也是MAE编码器只处理visible patches(75%算力节省)的前提。' },
  { cat:'vit', q:'SigLIP相比CLIP在batch size敏感性上的理论解释是什么？', opts:['SigLIP用了更大的温度参数','CLIP的InfoNCE loss中softmax需要全batch负样本做归一化常数Z，batch越大Z越准确；SigLIP的sigmoid loss每对独立计算，不依赖batch内其他样本','SigLIP用了梯度累积','没有理论差异，纯经验发现'], ans:1, exp:'InfoNCE的分母Σexp(sim)是在batch内所有负样本上求和，本质上是在估计配分函数Z。batch越小，Z的估计偏差越大（尤其是hard negative missing），直接影响梯度质量。SigLIP改为二元sigmoid loss: log σ(±sim)，每个正负对的loss计算完全独立于batch中其他样本，从根本上消除了对batch size的依赖。' },

  // ===== CLIP 深度 =====
  { cat:'clip', q:'CLIP对比学习中温度参数τ(temperature)的作用远比"缩放"复杂——它实际上在控制什么？', opts:['控制学习率','τ控制了学习到的特征空间中正负样本的间隔：τ越小，模型越关注hard negatives但容易过拟合；τ越大，loss更平滑但区分度降低','控制dropout率','控制模型深度'], ans:1, exp:'在InfoNCE中，τ缩放logits: sim/τ。τ→0时softmax变成argmax，loss完全由最hard的负样本主导（梯度剧烈）。τ→∞时所有负样本等权，loss退化。CLIP学习τ作为可训练参数(初始化为0.07)，最终收敛到约0.01。这个值决定了特征空间中正负对的余弦距离分布——太小会导致训练不稳定（梯度爆炸），太大会导致特征空间没有足够的区分度。' },
  { cat:'clip', q:'为什么CLIP在组合语义上失败（如"骑马的宇航员"vs"骑宇航员的马"），本质原因是什么？', opts:['训练数据太少','对比学习的bag-of-words特性：InfoNCE loss只比较全局相似度，不强制模型学习词序和空间关系的绑定','模型参数太少','分辨率太低'], ans:1, exp:'CLIP的文本编码器将句子编码为单一向量做全局匹配，训练目标只关心图文整体是否配对。这导致模型倾向学习概念共现(bag-of-concepts)而非结构化组合。"骑马的宇航员"和"骑宇航员的马"在bag-of-concepts层面几乎相同。NegCLIP、ARO benchmark等工作专门揭示了这一缺陷。解决方向包括hard negative mining和结构化对比目标。' },
  { cat:'clip', q:'EVA-CLIP在训练中使用了FLIP(随机mask图像patch)策略，这为什么能work而不损害性能？', opts:['Mask提供了数据增强','对比学习做全局匹配，不需要完整图像细节——mask掉50%的patch只影响局部信息但全局语义保留，同时节省50%视觉encoder计算量','Mask让模型学习重建','Mask防止过拟合'], ans:1, exp:'FLIP的insight是：CLIP的对比目标只需要全局语义匹配，不像MAE需要像素级重建。随机丢弃50%的patch后，全局语义信息基本保留（图像信息冗余），但ViT的计算量减半(因为只处理visible patches)。这使得在相同计算预算下可以用更大的batch或更长的训练。EVA-CLIP用此技巧将训练加速2×而性能不降。' },

  // ===== VLM 架构深度 =====
  { cat:'vlm', q:'LLaVA-1.5从Linear Projector升级到2层MLP的原因是什么？为什么不用更复杂的Q-Former？', opts:['MLP参数更少','MLP通过非线性变换提供了更好的跨模态特征适配，同时保留了所有spatial token信息；Q-Former虽然能压缩token数但会丢失细粒度视觉信息', 'Q-Former太慢','没有明确原因'], ans:1, exp:'Linear投影是纯线性映射，表达力有限。2层MLP加入了GELU非线性，能更好地将CLIP视觉特征"翻译"到LLM的语义空间。Q-Former(BLIP-2)用32-64个learnable query将~256个visual token压缩为固定数量，提升了效率但丢失了空间细节（对OCR/细粒度理解不利）。LLaVA选择保留全部visual token(~576个)交给LLM处理，以最大化信息保真度，这在计算允许的情况下是更好的选择。' },
  { cat:'vlm', q:'Dynamic Resolution(动态分辨率)策略在InternVL/LLaVA-NeXT中如何实现？核心trade-off是什么？', opts:['自适应resize到固定分辨率','将高分辨率图像切分为多个tile(如448×448)分别编码，加上一个缩略图全局tile，trade-off是visual token数量爆炸导致推理变慢','训练时用不同分辨率','只增大ViT的输入分辨率'], ans:1, exp:'高分辨率图(如1344×896)被切成6个448×448的tile+1个缩略图，每个tile经ViT编码得~256 token，总共7×256=1792 visual token。虽然OCR/细节任务大幅提升，但token数增加3-7×，导致LLM的prefill计算量和KV Cache线性增长。工程上需要做tile数量限制(如max_tiles=12)和token压缩(如pixel shuffle 2x2→1)来平衡。' },
  { cat:'vlm', q:'VLM中"视觉幻觉"的根因分析：以下哪个因素影响最大且最难解决？', opts:['Vision Encoder丢失了关键视觉信息（分辨率/遮挡）','LLM的语言先验过强——即使视觉信号弱，LLM也会基于文本统计规律"补全"看似合理但实际不存在的内容','Projector训练不足','数据标注有误'], ans:1, exp:'多项研究(如OPERA、VCD)表明，幻觉的主要来源是LLM端而非视觉端。即使给定perfect的视觉特征，LLM仍会因为language prior(如"桌上通常有杯子")而生成幻觉。证据：将visual tokens全部mask后，LLM仍能生成看似合理的描述。这说明LLM的text-only prior在与visual evidence竞争时常常"赢"了。缓解方法包括Visual Contrastive Decoding(VCD)、RLHF/DPO对齐、直接生成grounding box等。' },
  { cat:'vlm', q:'Qwen2-VL的Naive Dynamic Resolution与InternVL的Tile-based方案的本质区别是什么？', opts:['没有区别','Qwen2-VL用2D-RoPE对任意分辨率做原生处理，不需要切tile，避免了tile边界割裂语义；InternVL切tile后各tile独立编码，跨tile信息只能靠LLM层融合','Qwen2-VL分辨率更高','InternVL用了更大的ViT'], ans:1, exp:'InternVL的tile方案将图像切成独立tile，每个tile在ViT内独立编码——这意味着跨tile的物体/文字会被割裂，只能靠后续LLM层间接融合。Qwen2-VL的方案是将任意分辨率图像直接输入ViT(通过2D-RoPE处理非正方形position)，所有patch在self-attention中全局交互，保持了完整的空间信息。代价是ViT计算量更大，但信息保真度更高。' },
  { cat:'vlm', q:'为什么大多数VLM在Stage 1(Projector预训练)使用图文caption数据而非VQA数据？', opts:['Caption数据更便宜','Caption任务只需要描述图像内容(简单对齐任务)，不需要LLM的推理能力，让Projector专注学习视觉-语言特征空间映射而非task-specific能力','VQA数据不存在','效果一样'], ans:1, exp:'Stage 1的目标是视觉-语言对齐(alignment)而非指令遵循。Caption数据(如ShareGPT4V-PT)只要求模型描述图像内容，是纯粹的"看图说话"，梯度信号干净地指向Projector学习特征映射。如果用VQA数据，LLM需要同时学习推理逻辑，但此时Projector尚未训好，视觉信号是噪声，会污染LLM已有的推理能力(灾难性遗忘)。这就是为什么two-stage训练优于one-stage。' },

  // ===== 训练策略深度 =====
  { cat:'training', q:'混合精度训练中，loss scaling的具体机制是什么？为什么需要动态调整scale factor？', opts:['放大loss值使FP16的小梯度不被flush to zero，scale factor过大会导致梯度溢出(inf)所以需要动态调整','缩小loss加速收敛','固定scale=1024即可','Loss scaling只影响精度不影响训练'], ans:0, exp:'FP16最小正常值≈6e-8，很多梯度值小于此值会变成0。Loss scaling将loss乘以S(如1024)，使梯度放大S倍进入FP16可表示范围，更新参数前再除以S还原。但S太大→梯度溢出(inf/nan)，S太小→仍有underflow。动态策略：每N步尝试增大S（2×），遇到inf就减半并跳过该step。这个ping-pong过程使S自适应到梯度分布的合理范围。' },
  { cat:'training', q:'FSDP(Fully Sharded Data Parallel)和DeepSpeed ZeRO-3的核心区别是什么？', opts:['功能完全相同','FSDP是PyTorch原生实现,用FlatParameter将多个参数打包分片+NCCL通信；ZeRO-3是独立库,逐参数分片+自定义通信算子,灵活性和优化空间更大','FSDP只支持single-node','ZeRO-3不支持混合精度'], ans:1, exp:'虽然都实现params/grads/optimizer states全分片，但实现哲学不同。FSDP将模型的多个参数flatten成FlatParameter后切分，通信用all-gather/reduce-scatter，与PyTorch autograd深度耦合。ZeRO-3逐parameter切分，有自己的partition/gather逻辑和更灵活的offload策略(CPU/NVMe)。实际性能：在超大规模(1000+GPU)上ZeRO-3+Megatron的3D并行更成熟；单机多卡FSDP更易用。' },
  { cat:'training', q:'VLM训练中，为什么Stage 2解冻ViT有时反而降低性能？', opts:['ViT参数太多','当SFT数据量不足时，ViT在小数据上微调会导致灾难性遗忘通用视觉能力，且与LLM的学习速率不匹配导致训练不稳定','ViT已经是最优的','解冻ViT永远更好'], ans:1, exp:'ViT在大规模数据(如CLIP 4亿图文对)上预训练的通用视觉能力是其核心价值。若SFT数据只有几十万条，解冻ViT后它会快速过拟合到SFT数据的分布上，丢失通用特征提取能力。且ViT和LLM对学习率的需求差异大(ViT通常需要更小lr)，不当的统一lr会导致一方训坏。InternVL采用progressive unfreezing+分层lr来缓解此问题。' },
  { cat:'training', q:'在数据配比(data mixing)方面，VLM SFT阶段为什么通常需要混入一部分纯文本数据？', opts:['增加数据量','防止LLM的纯语言能力退化(catastrophic forgetting)，维持指令遵循和推理能力','纯文本数据更便宜','没有必要'], ans:1, exp:'VLM的SFT数据以视觉指令为主，如果不混入纯文本对话/推理数据，LLM的语言能力会因为训练分布偏移而退化——表现为纯文本问答质量下降、格式遵循能力变差。典型比例是70-80%视觉数据+20-30%纯文本数据。Qwen2-VL/InternVL都采用了这种混合训练策略。这是VLM工程中一个容易被忽视但影响巨大的细节。' },

  // ===== 推理优化深度 =====
  { cat:'inference', q:'PagedAttention的block大小选择涉及什么trade-off？', opts:['没有trade-off，越大越好','block太大→内部碎片(最后一个block浪费)和内存利用率低；block太小→block table管理开销大且CUDA kernel效率低(不够coalesced)','block大小不影响性能','只影响延迟不影响吞吐'], ans:1, exp:'类比OS的page size选择：vLLM默认block_size=16 tokens。如果序列长度不是16的倍数，最后一个block会有1-15个slot浪费(内部碎片)。block太小(如1)则block table很大，且CUDA memory access pattern不够对齐。16是经验最优值——在A100上对齐了128B cacheline，碎片率约8%。SGLang等框架在此基础上进一步优化了RadixAttention来共享前缀的KV Cache blocks。' },
  { cat:'inference', q:'Speculative Decoding在什么场景下加速比最高？什么场景下几乎无效？', opts:['任何场景都一样','确定性高的任务(代码/翻译)加速比高(因为draft model准确率高)；创意性任务(开放问答/写作)基本无效(因为draft model猜不准，大部分被reject)','只在长序列有效','只在小模型有效'], ans:1, exp:'Speculative Decoding的加速比≈1/(1-α)^γ，其中α是draft model的acceptance rate，γ是每次猜测的token数。代码生成等deterministic任务中，7B draft model猜70B target的准确率可达80-90%，加速3-5×。但在creative writing等任务中，distribution mismatch大，acceptance rate可能只有30-40%，加速不到1.5×甚至因overhead变慢。这也是为什么EAGLE等工作在spec decoding的draft model设计上做了大量工作。' },
  { cat:'inference', q:'AWQ (Activation-Aware Weight Quantization) 相比GPTQ的核心改进insight是什么？', opts:['使用更低bit量化','发现1%的salient weights(对应激活值大的通道)对性能影响远超其他99%，对这些通道做per-channel scaling后再量化，比GPTQ的per-column量化重建更有效','使用不同的量化算法','AWQ更快'], ans:1, exp:'AWQ的核心观察：权重的"重要性"不取决于权重值本身大小，而取决于对应输入激活的magnitude。对激活值大的通道，权重的小量化误差会被放大。AWQ对这些salient通道做等效的scaling transformation（数学上不改变输出），让量化误差分布更均匀。相比GPTQ需要校准数据做逐列weight reconstruction，AWQ只需要很少的校准数据且速度更快。' },
  { cat:'inference', q:'Prefix Caching(如SGLang的RadixAttention)在哪些场景下收益最大？实现的关键数据结构是什么？', opts:['所有场景收益相同','共享system prompt/few-shot examples的场景收益最大(如chatbot)；用Radix Tree索引KV Cache blocks，支持最长前缀匹配和LRU淘汰','只在短序列有效','用哈希表'], ans:1, exp:'当多个请求共享相同前缀(如system prompt、few-shot examples、RAG检索结果)时，Prefix Caching避免了重复计算这些前缀的KV Cache。SGLang用Radix Tree(前缀树)管理所有cached prefix的KV blocks，每次新请求先做最长前缀匹配，命中的块直接复用。数据结构支持O(L)查找(L=前缀长度)和LRU淘汰策略。在customer service chatbot(有长system prompt)场景下可节省50-80%的prefill计算。' },

  // ===== Tokenization 深度 =====
  { cat:'tokenization', q:'为什么VQ-VAE训练中需要codebook的EMA更新和commitment loss？没有它们会怎样？', opts:['只是为了加速收敛','没有commitment loss→encoder输出会远离codebook(量化误差大)；没有EMA→codebook利用率极低(codebook collapse),大部分code不被使用','不需要这些技巧','只需要其中一个'], ans:1, exp:'VQ-VAE的量化用argmin找最近code，但梯度无法通过argmin传播。Straight-through estimator解决了encoder梯度，但encoder可能学成"无视codebook"的表示。Commitment loss = ‖z_e - sg(e)‖²强制encoder输出靠近codebook。EMA更新codebook向量向被匹配的encoder输出滑动，避免了codebook中大量code从不被选中(collapse)。二者缺一不可。' },
  { cat:'tokenization', q:'LLaMA 3的词表从32K扩展到128K的设计考量和工程影响是什么？', opts:['纯粹为了支持更多语言','编码效率提升(同样文本需要更少token)降低推理成本，但embedding层参数增加8GB(128K×dim=16384×FP16)，且稀有token的embedding可能训练不充分','没有影响','只影响训练速度'], ans:1, exp:'词表越大→平均每个token承载更多信息→同样长度文本用更少token表示(编码效率提升~15%)→推理时KV Cache更短、生成步数更少。但trade-off：(1)Embedding和LM head的参数量=vocab_size×hidden_dim，128K×8192=1B参数仅在embedding上；(2)低频token的embedding因训练不充分而质量低；(3)softmax在128K上的计算变慢。LLaMA 3通过足够大的训练数据(15T tokens)缓解了稀有token训练不充分的问题。' },

  // ===== 推理/CoT 深度 =====
  { cat:'reasoning', q:'DeepSeek-R1的"Aha Moment"是如何通过纯RL涌现出来的？这对模型能力意味着什么？', opts:['通过SFT数据模仿','在纯RL训练(使用GRPO+规则reward)中，模型自发学会了在推理链中"wait, let me reconsider"的自我反思行为，未经任何人类标注的CoT示范','手动编程的规则','随机出现的'], ans:1, exp:'DeepSeek-R1-Zero只用结果正确性作为reward(没有CoT SFT)，模型在RL训练中自发涌现了"let me reconsider"、"alternatively"等自我纠错行为。这意味着足够规模的RL+准确的reward signal可以让模型自主发展出推理策略，而不需要人类示范。这是一个深刻的发现：推理能力可以是emergent behavior而非imitated behavior。但注意R1-Zero的readability很差，所以最终R1还是加了SFT cold-start。' },
  { cat:'reasoning', q:'在test-time compute scaling中，增加更多compute的两种主要策略是什么？它们的scaling行为有何不同？', opts:['增加模型大小和训练数据','Sequential revision(生成后反复修改)和Parallel sampling(独立生成多个候选后选最好的)；Parallel sampling log-linear提升，Sequential更高效但依赖verifier质量','增加batch size和学习率','Fine-tuning和prompting'], ans:1, exp:'Parallel sampling：独立生成N个响应，用verifier/majority voting选最佳。提升与log(N)近似正比(因为抽到好答案是概率事件)。Sequential revision：迭代修改同一个响应(如重新审视推理步骤)，在有好verifier时更compute-efficient。DeepMind的research表明：对于难题，sequential更好；对于中等题，parallel就够了。最优策略是自适应地分配compute——简单题少compute、难题多compute。' },
  { cat:'reasoning', q:'Process Reward Model(PRM)和Outcome Reward Model(ORM)的核心区别及各自优劣？', opts:['PRM评估每个推理步骤的正确性，ORM只评估最终答案。PRM信号更密集但标注成本极高且容易reward hacking，ORM信号稀疏但标注简单','PRM更快','ORM更准确','没有明显区别'], ans:0, exp:'ORM只给最终结果打分(对/错)，信号稀疏导致credit assignment困难(不知道哪步出错)。PRM对每一步推理打分，提供密集监督信号，能更好地引导模型的推理过程(best-of-N with PRM远优于ORM)。但PRM的标注需要数学/逻辑专家逐步验证，成本是ORM的10-100×。且PRM容易被hack——模型可能学到"写出PRM喜欢的格式"而非真正推理。Math-Shepherd等工作用自动化方法降低PRM标注成本。' },

  // ===== 生成模型深度 =====
  { cat:'generation', q:'Classifier-Free Guidance(CFG)的数学原理是什么？guidance scale对生成质量的影响？', opts:['简单地增大条件权重','在噪声预测中做条件和无条件的线性外推: ε̃ = ε_uncond + s×(ε_cond - ε_uncond)，s>1时增强条件一致性但损害多样性和引入伪影','去除分类器','降低噪声级别'], ans:1, exp:'CFG的核心公式使模型预测"更偏向条件"的噪声。s=1退化为标准条件生成；s=7-12是SD的常用范围，增强文本一致性；s过大(>15)导致过饱和/伪影——因为线性外推超出了模型训练分布。数学上CFG等价于在对数概率空间做p_guided ∝ p_uncond × (p_cond/p_uncond)^s，即提升条件与无条件的似然比。训练时需要random dropout条件(如10%概率不给text)来让模型同时学习条件和无条件生成。' },
  { cat:'generation', q:'Flow Matching相比Diffusion Model的理论优势是什么？SD3为什么选择了它？', opts:['参数量更少','Flow Matching直接学习概率路径的速度场(ODE)，可以用直线路径(Rectified Flow)减少采样步数和NFE，不需要复杂的noise schedule设计','训练数据更少','只是换了个名字'], ans:1, exp:'Diffusion使用SDE(随机微分方程)描述加噪/去噪过程，需要精心设计noise schedule且采样步数多(20-50步)。Flow Matching学习确定性ODE的速度场v(x_t,t)，直接从噪声到图像画一条"直线"(Rectified Flow)。好处：(1)路径更短→更少采样步数(4-8步)；(2)不需要noise schedule；(3)训练目标更简单(MSE回归v)。SD3采用RF + MMDiT，在4步采样下质量就很高。' },
  { cat:'generation', q:'视频生成模型(如Sora类)中，temporal consistency的核心难题是什么？', opts:['显存不够','跨帧的attention复杂度O(T²×N²)爆炸(T=帧数,N=spatial tokens)，且3D VAE难以保证时域连贯的latent表示；temporal attention做不到真正的长程时域依赖','数据不够','分辨率不够'], ans:1, exp:'假设每帧256 token、生成120帧：如果用full 3D attention，序列长度=120×256=30720，attention矩阵>900M entries。即使用spatial-temporal factorized attention，temporal window也有限(通常8-16帧)，长程动作一致性仍是难题。3D VAE如果temporal compression太aggressive会丢失运动细节。这也是目前视频生成"闪烁/不连贯"的根本原因。解决方向包括motion latent、hierarchical generation、temporal super-resolution。' },

  // ===== RAG 深度 =====
  { cat:'rag', q:'当retrieval质量不高时，LLM在RAG中的典型失败模式是什么？如何缓解？', opts:['不读retrieval结果直接回答','faithfully但错误地基于低质量检索结果生成答案(被noise context误导)，比不用RAG更差。缓解：自适应检索(判断是否需要检索)、self-RAG(生成后自我验证)、检索结果reranking','检索变慢','生成空回复'], ans:1, exp:'Lost-in-the-Middle研究表明LLM倾向信任context中的信息(尤其是位置靠前/靠后的)，即使检索到错误文档，模型也会基于它们生成看似有理但实际错误的答案。这比模型纯靠参数知识回答更危险(用户更信任"有出处"的答案)。Self-RAG让模型生成<retrieve>/<no_retrieve>标签判断是否需要检索、<critique>标签评估检索相关性、<support>标签验证生成内容是否faithfully grounded。这是当前工业级RAG的关键改进。' },
  { cat:'rag', q:'向量检索的ANN(Approximate Nearest Neighbor)中，HNSW和IVF-PQ各自的适用场景？', opts:['功能完全相同','HNSW: 高召回+低延迟但内存占用大(需存原始向量)，适合<10M文档；IVF-PQ: 通过Product Quantization压缩向量+倒排索引，内存占用小10×但召回略低，适合>100M文档','HNSW更新更快','IVF-PQ精度更高'], ans:1, exp:'HNSW(Hierarchical Navigable Small World)构建多层图结构,查询时从高层粗搜到底层精搜,recall@10可达99%+但需要在内存中保存所有原始向量(768维*4B*10M=30GB)。IVF-PQ将向量空间划分为聚类(IVF),每个向量用Product Quantization压缩到32-64字节,10M向量只需~1GB内存。适用于大规模场景。关键参数调优：nprobe(IVF搜索聚类数)和ef(HNSW搜索宽度)直接影响recall-latency tradeoff。' },

  // ===== 前沿架构深度 =====
  { cat:'frontier', q:'Mamba的selective state space机制与传统S4的核心区别是什么？为什么这对语言建模至关重要？', opts:['Mamba参数更多','Mamba让SSM的参数(Δ,B,C)成为输入依赖(input-dependent)，实现了内容感知的选择性遗忘/记忆，而S4用固定参数无法做内容选择','Mamba用了更大的state','Mamba加了attention'], ans:1, exp:'S4的A/B/C矩阵是固定可学习参数，对所有输入token使用相同的状态转移方程——无法实现"忘记不重要的、记住关键的"选择性。Mamba让B/C/Δ通过线性投影从当前输入得到，实现了input-dependent gating：当Δ大时，新输入重写state(遗忘旧信息)；Δ小时保持state(记忆)。这等效于实现了一种硬件高效的data-dependent选择性注意力。但代价是丧失了S4优雅的频域快速算法，Mamba改用hardware-aware的scan实现。' },
  { cat:'frontier', q:'DeepSeek-V3的FP8训练中，最关键的工程挑战和解决方案是什么？', opts:['精度损失可忽略','FP8的dynamic range极窄(E4M3: ±448)，outlier activation会溢出。DeepSeek-V3用fine-grained quantization(per-tile而非per-tensor)大幅降低量化误差，实际训练loss曲线与BF16几乎重合','只需要简单cast即可','FP8只用在推理不用在训练'], ans:1, exp:'FP8 E4M3的表示范围远小于BF16(±3.39e38)。大模型训练中activation存在outlier，per-tensor quantization时outlier占据大量dynamic range导致其他值精度极低。DeepSeek-V3的解决方案：(1)Fine-grained quantization：将大矩阵分成128×128的tile，每个tile独立计算scale factor，确保每个tile的量化利用率最优；(2)只在GEMM中用FP8，accumulation用FP32防止精度累积；(3)训练过程中在线完成calibration。最终实现了2.15倍计算效率提升，loss与BF16基线差异<0.25%。' },
  { cat:'frontier', q:'Jamba/Zamba等混合架构(Mamba+Attention)为什么把Attention层放在特定位置而非均匀分布？', opts:['随机放置效果一样','Attention层提供全局信息回溯能力来弥补Mamba的"遗忘"特性，放在模型的1/3和2/3等关键位置形成信息"检查点"，比均匀分布更高效','只是训练方便','Attention层的位置不重要'], ans:1, exp:'Mamba作为RNN类模型，状态空间有限，处理长序列时inevitably遗忘早期信息。在关键深度位置插入Attention层，让模型有机会"回溯"整个序列，修补Mamba累积的信息损失。为什么不均匀分布？因为前几层(特征提取)和最后几层(输出映射)不太需要全局回溯，中间层(信息整合)最需要。Jamba用1:7(每8层1层attention)就在保持Mamba的线性复杂度优势的同时恢复了大部分attention性能。工程上这些Attention层是KV Cache的唯一来源，KV Cache比纯Transformer小7×。' },
];
